-- Script SQL pour créer la base de données FSC Survey
-- À exécuter dans Cloudflare D1 Dashboard

CREATE TABLE survey_responses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_soumission DATETIME NOT NULL,
    prenom TEXT NOT NULL,
    pays TEXT NOT NULL,
    adresse TEXT,
    sexe TEXT NOT NULL,
    domaine TEXT NOT NULL,
    annee TEXT NOT NULL,
    etablissement TEXT NOT NULL,
    experience TEXT NOT NULL,
    cours_ia TEXT NOT NULL,
    explication_ia TEXT,
    usage_ia TEXT NOT NULL,
    usages_ia TEXT,
    problemes TEXT,
    probleme_principal TEXT,
    processus_repetitifs TEXT,
    processus_automatise TEXT,
    heures_economisees INTEGER,
    quantite_donnees TEXT NOT NULL,
    competences TEXT,
    duree_formation TEXT,
    format_formation TEXT,
    prix_formation TEXT,
    prix_converti TEXT,
    obstacles TEXT,
    equipements TEXT,
    raisons_pas_solutions TEXT,
    obstacle_principal TEXT,
    formation_securite TEXT,
    niveau_securite TEXT,
    pratiques_securite TEXT,
    risques_cyber TEXT,
    importance_ia_carriere TEXT,
    secteur_souhaite TEXT,
    demande_emploi TEXT,
    competences_importance TEXT,
    preparation_emploi TEXT,
    manque_preparation TEXT,
    entreprises_innovantes TEXT,
    ia_cours TEXT,
    ia_ameliore_enseignement TEXT,
    risques_ia_enseignement TEXT,
    risques_details TEXT,
    recommandation_education TEXT,
    vision_tech TEXT,
    interets_communaute TEXT,
    email TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insérer des données de test
INSERT INTO survey_responses (
    date_soumission, prenom, pays, adresse, sexe, domaine, annee, etablissement, experience,
    cours_ia, explication_ia, usage_ia, usages_ia,
    problemes, probleme_principal, processus_repetitifs, processus_automatise, heures_economisees, quantite_donnees,
    competences, duree_formation, format_formation, prix_formation, prix_converti,
    obstacles, equipements, raisons_pas_solutions, obstacle_principal,
    formation_securite, niveau_securite, pratiques_securite, risques_cyber,
    importance_ia_carriere, secteur_souhaite, demande_emploi, competences_importance, preparation_emploi, manque_preparation, entreprises_innovantes,
    ia_cours, ia_ameliore_enseignement, risques_ia_enseignement, risques_details,
    recommandation_education, vision_tech, interets_communaute, email
) VALUES (
    datetime('now'), 'Test', 'Maroc', 'Casablanca', 'Homme', 'Informatique', '3ème année', 'Université Test', '1-2 ans',
    'Oui', 'Intelligence Artificielle', 'Oui, régulièrement', 'Recherche, Analyse de données',
    'Manque de compétences', 'Formation inadéquate', 'Saisie de données', '50%', 10, '100-500 Go',
    'Python, Machine Learning', '3-6 mois', 'En ligne', '5000-10000 MAD', '5000-10000 MAD',
    'Coût élevé', 'Ordinateur portable', 'Prix trop élevé', 'Coût',
    'Non', 'Débutant', 'Mots de passe forts', 'Vol de données',
    'Très important', 'Tech', 'Élevée', 'IA > Data > Cloud', 'Formation spécialisée', 'Pratique insuffisante', 'Google, Microsoft',
    'Oui', 'Oui', 'Désinformation', 'Contenu généré automatiquement',
    'Plus de cours pratiques', 'L''IA transformera tous les secteurs', 'Échanges, Projets collaboratifs', 'test@fsc.com'
);